/* Generated by scripts/generate-posix.py. */
_Static_assert(sizeof(struct timespec) == 16, "Linux ABI layout: struct timespec");
_Static_assert(sizeof(((struct timespec *)0)->tv_nsec) == 8, "Linux ABI layout: struct timespec");
_Static_assert(sizeof(gid_t) == 4, "Linux ABI layout: gid_t");
_Static_assert(sizeof(struct tms) == 32, "Linux ABI layout: struct tms");
static int64_t service_posix(struct bridge_host *h, struct posix_request *request) {
    uint64_t *a = request->args;
    switch (request->operation) {
    case PX_CHOWN: {
        uid_t owner = (uid_t)a[1];
        gid_t group = (gid_t)a[2];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return chown(path, owner, group);
    }
    case PX_LCHOWN: {
        uid_t owner = (uid_t)a[1];
        gid_t group = (gid_t)a[2];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        return lchown(path, owner, group);
    }
    case PX_FCHOWN: {
        uid_t owner = (uid_t)a[1];
        gid_t group = (gid_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return fchown(descriptor, owner, group);
    }
    case PX_TRUNCATE: {
        off_t length = (off_t)a[1];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return truncate(path, length);
    }
    case PX_FTRUNCATE: {
        off_t length = (off_t)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return ftruncate(descriptor, length);
    }
    case PX_PREAD: {
        size_t count = (size_t)a[2];
        off_t offset = (off_t)a[3];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        void *buffer = memory(h, a[1], count);
        if (!buffer && (count) != 0)
            return -1;
        return pread(descriptor, buffer, count, offset);
    }
    case PX_PWRITE: {
        size_t count = (size_t)a[2];
        off_t offset = (off_t)a[3];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const void *buffer = memory(h, a[1], count);
        if (!buffer && (count) != 0)
            return -1;
        return pwrite(descriptor, buffer, count, offset);
    }
    case PX_READLINKAT: {
        size_t size = (size_t)a[3];
        int directory = (int)a[0] == -2 ? AT_FDCWD : fd(h, (int)a[0]);
        if (directory < 0 && directory != AT_FDCWD)
            return -1;
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[1], path_storage, 0);
        if (!path)
            return -1;
        char *buffer = memory(h, a[2], size);
        if (!buffer && (size) != 0)
            return -1;
        return readlinkat(directory, path, buffer, size);
    }
    case PX_UNLINKAT: {
        int directory = (int)a[0] == -2 ? AT_FDCWD : fd(h, (int)a[0]);
        if (directory < 0 && directory != AT_FDCWD)
            return -1;
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[1], path_storage, 0);
        if (!path)
            return -1;
        int flags = at_flags(a[2]);
        if (flags < 0)
            return -1;
        return unlinkat(directory, path, flags);
    }
    case PX_FLOCK: {
        int operation = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return flock(descriptor, operation);
    }
    case PX_POSIX_FALLOCATE: {
        off_t offset = (off_t)a[1];
        off_t length = (off_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        int error = posix_fallocate(descriptor, offset, length);
        if (error) {
            errno = error;
            return -1;
        }
        return 0;
    }
    case PX_MKNOD: {
        mode_t mode = (mode_t)a[1];
        dev_t device = (dev_t)a[2];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        return mknod(path, mode, device);
    }
    case PX_FUTIMENS: {
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const struct timespec *times = a[1] ? memory(h, a[1], 2 * sizeof(struct timespec)) : NULL;
        if (a[1] && !times)
            return -1;
        return futimens(descriptor, times);
    }
    case PX_GETSID: {
        pid_t process = (pid_t)a[0];
        return getsid(process);
    }
    case PX_GETPRIORITY: {
        int which = (int)a[0];
        id_t who = (id_t)a[1];
        return getpriority(which, who);
    }
    case PX_SETPRIORITY: {
        int which = (int)a[0];
        id_t who = (id_t)a[1];
        int priority = (int)a[2];
        return setpriority(which, who, priority);
    }
    case PX_SETHOSTNAME: {
        size_t length = (size_t)a[1];
        const char *name = memory(h, a[0], length);
        if (!name && (length) != 0)
            return -1;
        return sethostname(name, length);
    }
    case PX_GETHOSTID: {
        return gethostid();
    }
    case PX_SCHED_GET_PRIORITY_MAX: {
        int policy = (int)a[0];
        return sched_get_priority_max(policy);
    }
    case PX_SCHED_GET_PRIORITY_MIN: {
        int policy = (int)a[0];
        return sched_get_priority_min(policy);
    }
    case PX_SCHED_GETAFFINITY: {
        pid_t process = (pid_t)a[0];
        size_t size = (size_t)a[1];
        cpu_set_t *mask = memory(h, a[2], size);
        if (!mask && (size) != 0)
            return -1;
        return sched_getaffinity(process, size, mask);
    }
    case PX_SCHED_SETAFFINITY: {
        pid_t process = (pid_t)a[0];
        size_t size = (size_t)a[1];
        const cpu_set_t *mask = memory(h, a[2], size);
        if (!mask && (size) != 0)
            return -1;
        return sched_setaffinity(process, size, mask);
    }
    case PX_SOCKET: {
        int domain = (int)a[0];
        int type = (int)a[1];
        int protocol = (int)a[2];
        return save_fd(h, socket(domain, type, protocol), 0);
    }
    case PX_BIND: {
        socklen_t length = (socklen_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const struct sockaddr *address = memory(h, a[1], length);
        if (!address && (length) != 0)
            return -1;
        return bind(descriptor, address, length);
    }
    case PX_CONNECT: {
        socklen_t length = (socklen_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const struct sockaddr *address = memory(h, a[1], length);
        if (!address && (length) != 0)
            return -1;
        return connect(descriptor, address, length);
    }
    case PX_LISTEN: {
        int backlog = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return listen(descriptor, backlog);
    }
    case PX_SHUTDOWN: {
        int how = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return shutdown(descriptor, how);
    }
    case PX_SEND: {
        size_t size = (size_t)a[2];
        int flags = (int)a[3];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const void *buffer = memory(h, a[1], size);
        if (!buffer && (size) != 0)
            return -1;
        return send(descriptor, buffer, size, flags);
    }
    case PX_RECV: {
        size_t size = (size_t)a[2];
        int flags = (int)a[3];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        void *buffer = memory(h, a[1], size);
        if (!buffer && (size) != 0)
            return -1;
        return recv(descriptor, buffer, size, flags);
    }
    case PX_SENDTO: {
        size_t size = (size_t)a[2];
        int flags = (int)a[3];
        socklen_t length = (socklen_t)a[5];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const void *buffer = memory(h, a[1], size);
        if (!buffer && (size) != 0)
            return -1;
        const struct sockaddr *address = a[4] ? memory(h, a[4], length) : NULL;
        if (a[4] && !address)
            return -1;
        return sendto(descriptor, buffer, size, flags, address, length);
    }
    case PX_GETRANDOM: {
        size_t size = (size_t)a[1];
        unsigned int flags = (unsigned int)a[2];
        void *buffer = memory(h, a[0], size);
        if (!buffer && (size) != 0)
            return -1;
        return getrandom(buffer, size, flags);
    }
    case PX_INOTIFY_INIT1: {
        int flags = open_flags(a[0]);
        return save_fd(h, inotify_init1(flags), 0);
    }
    case PX_INOTIFY_ADD_WATCH: {
        uint32_t mask = (uint32_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[1], path_storage, 1);
        if (!path)
            return -1;
        return inotify_add_watch(descriptor, path, mask);
    }
    case PX_INOTIFY_RM_WATCH: {
        int watch = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return inotify_rm_watch(descriptor, watch);
    }
    case PX_POSIX_OPENPT: {
        int flags = open_flags(a[0]);
        return save_fd(h, posix_openpt(flags), 0);
    }
    case PX_GRANTPT: {
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return grantpt(descriptor);
    }
    case PX_UNLOCKPT: {
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return unlockpt(descriptor);
    }
    case PX_PTSNAME_R: {
        size_t size = (size_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        char *buffer = memory(h, a[1], size);
        if (!buffer && (size) != 0)
            return -1;
        int error = ptsname_r(descriptor, buffer, size);
        if (error) {
            errno = error;
            return -1;
        }
        return 0;
    }
    case PX_TTYNAME_R: {
        size_t size = (size_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        char *buffer = memory(h, a[1], size);
        if (!buffer && (size) != 0)
            return -1;
        int error = ttyname_r(descriptor, buffer, size);
        if (error) {
            errno = error;
            return -1;
        }
        return 0;
    }
    case PX_TCFLOW: {
        int action = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return tcflow(descriptor, action);
    }
    case PX_SHM_UNLINK: {
        const char *name = string(h, a[0]);
        if (!name)
            return -1;
        return shm_unlink(name);
    }
    case PX_CLOCK_SETTIME: {
        clockid_t clock = native_clock(a[0]);
        if (clock < 0) {
            errno = EINVAL;
            return -1;
        }
        const struct timespec *value = memory(h, a[1], sizeof(struct timespec));
        if (!value && (sizeof(struct timespec)) != 0)
            return -1;
        return clock_settime(clock, value);
    }
    case PX_REBOOT: {
        int command = (int)a[0];
        return reboot(command);
    }
    case PX_SWAPON: {
        int flags = (int)a[1];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return swapon(path, flags);
    }
    case PX_SWAPOFF: {
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return swapoff(path);
    }
    case PX_UMOUNT2: {
        int flags = (int)a[1];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return umount2(path, flags);
    }
    case PX_SETNS: {
        int type = (int)a[1];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        return setns(descriptor, type);
    }
    case PX_UNSHARE: {
        int flags = (int)a[0];
        return unshare(flags);
    }
    case PX_RENAME: {
        char old_storage[BRIDGE_PATH_SIZE];
        const char *old = path_string_mode(h, a[0], old_storage, 0);
        if (!old)
            return -1;
        char new_storage[BRIDGE_PATH_SIZE];
        const char *new = path_string_mode(h, a[1], new_storage, 0);
        if (!new)
            return -1;
        return rename(old, new);
    }
    case PX_MEMFD_CREATE: {
        unsigned flags = (unsigned)a[1];
        const char *name = string(h, a[0]);
        if (!name)
            return -1;
        return save_fd(h, memfd_create(name, flags), 0);
    }
    case PX_SHM_OPEN: {
        mode_t mode = (mode_t)a[2];
        const char *name = string(h, a[0]);
        if (!name)
            return -1;
        int flags = open_flags(a[1]);
        return save_fd(h, shm_open(name, flags, mode), 0);
    }
    case PX_MOUNT: {
        unsigned long flags = (unsigned long)a[3];
        char source_storage[BRIDGE_PATH_SIZE];
        const char *source = a[0] ? path_string_mode(h, a[0], source_storage, 1) : NULL;
        if (a[0] && !source)
            return -1;
        char target_storage[BRIDGE_PATH_SIZE];
        const char *target = path_string_mode(h, a[1], target_storage, 1);
        if (!target)
            return -1;
        const char *type = a[2] ? string(h, a[2]) : NULL;
        if (a[2] && !type)
            return -1;
        const void *data = a[4] ? string(h, a[4]) : NULL;
        if (a[4] && !data)
            return -1;
        return mount(source, target, type, flags, data);
    }
    case PX_INITGROUPS: {
        gid_t group = (gid_t)a[1];
        const char *user = string(h, a[0]);
        if (!user)
            return -1;
        return initgroups(user, group);
    }
    case PX_SETGROUPS: {
        int count = (int)a[0];
        const gid_t *groups = memory(h, a[1], count * sizeof(gid_t));
        if (!groups && (count * sizeof(gid_t)) != 0)
            return -1;
        return setgroups(count, groups);
    }
    case PX_SETUID: {
        uid_t id = (uid_t)a[0];
        return setuid(id);
    }
    case PX_SETGID: {
        gid_t id = (gid_t)a[0];
        return setgid(id);
    }
    case PX_SETRESUID: {
        uid_t r = (uid_t)a[0];
        uid_t e = (uid_t)a[1];
        uid_t s = (uid_t)a[2];
        return setresuid(r, e, s);
    }
    case PX_SETRESGID: {
        gid_t r = (gid_t)a[0];
        gid_t e = (gid_t)a[1];
        gid_t s = (gid_t)a[2];
        return setresgid(r, e, s);
    }
    case PX_EPOLL_CREATE1: {
        int flags = open_flags(a[0]);
        return save_fd(h, epoll_create1(flags), 0);
    }
    case PX_SCHED_YIELD: {
        return sched_yield();
    }
    case PX_PAUSE: {
        return pause();
    }
    case PX_MLOCK: {
        size_t size = (size_t)a[1];
        const void *address = memory(h, a[0], size);
        if (!address && (size) != 0)
            return -1;
        return mlock(address, size);
    }
    case PX_MUNLOCK: {
        size_t size = (size_t)a[1];
        const void *address = memory(h, a[0], size);
        if (!address && (size) != 0)
            return -1;
        return munlock(address, size);
    }
    case PX_MLOCKALL: {
        int flags = (int)a[0];
        return mlockall(flags);
    }
    case PX_MUNLOCKALL: {
        return munlockall();
    }
    case PX_MSGGET: {
        key_t key = (key_t)a[0];
        int flags = (int)a[1];
        return msgget(key, flags);
    }
    case PX_SHMGET: {
        key_t key = (key_t)a[0];
        size_t size = (size_t)a[1];
        int flags = (int)a[2];
        return shmget(key, size, flags);
    }
    case PX_SEMGET: {
        key_t key = (key_t)a[0];
        int count = (int)a[1];
        int flags = (int)a[2];
        return semget(key, count, flags);
    }
    case PX_CHROOT: {
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        return chroot(path);
    }
    case PX_UTIMENSAT: {
        int directory = (int)a[0] == -2 ? AT_FDCWD : fd(h, (int)a[0]);
        if (directory < 0 && directory != AT_FDCWD)
            return -1;
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path =
            path_string_mode(h, a[1], path_storage, !(at_flags(a[3]) & AT_SYMLINK_NOFOLLOW));
        if (!path)
            return -1;
        const struct timespec *times = a[2] ? memory(h, a[2], 2 * sizeof(struct timespec)) : NULL;
        if (a[2] && !times)
            return -1;
        int flags = at_flags(a[3]);
        if (flags < 0)
            return -1;
        return utimensat(directory, path, times, flags);
    }
    case PX_CLOCK_GETRES: {
        clockid_t clock = native_clock(a[0]);
        if (clock < 0) {
            errno = EINVAL;
            return -1;
        }
        struct timespec *value = a[1] ? memory(h, a[1], sizeof(struct timespec)) : NULL;
        if (a[1] && !value)
            return -1;
        return clock_getres(clock, value);
    }
    case PX_TIMES: {
        struct tms *value = a[0] ? memory(h, a[0], sizeof(struct tms)) : NULL;
        if (a[0] && !value)
            return -1;
        return times(value);
    }
    case PX_FACCESSAT: {
        int mode = (int)a[2];
        int directory = (int)a[0] == -2 ? AT_FDCWD : fd(h, (int)a[0]);
        if (directory < 0 && directory != AT_FDCWD)
            return -1;
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path =
            path_string_mode(h, a[1], path_storage, !(at_flags(a[3]) & AT_SYMLINK_NOFOLLOW));
        if (!path)
            return -1;
        int flags = at_flags(a[3]);
        if (flags < 0)
            return -1;
        return faccessat(directory, path, mode, flags);
    }
    case PX_GETXATTR: {
        size_t size = (size_t)a[3];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return getxattr(path, name, value, size);
    }
    case PX_SETXATTR: {
        size_t size = (size_t)a[3];
        int flags = (int)a[4];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        const void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return setxattr(path, name, value, size, flags);
    }
    case PX_LISTXATTR: {
        size_t size = (size_t)a[2];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        char *list = a[1] ? memory(h, a[1], size) : NULL;
        if (a[1] && !list)
            return -1;
        return listxattr(path, list, size);
    }
    case PX_REMOVEXATTR: {
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 1);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        return removexattr(path, name);
    }
    case PX_LGETXATTR: {
        size_t size = (size_t)a[3];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return lgetxattr(path, name, value, size);
    }
    case PX_LSETXATTR: {
        size_t size = (size_t)a[3];
        int flags = (int)a[4];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        const void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return lsetxattr(path, name, value, size, flags);
    }
    case PX_LLISTXATTR: {
        size_t size = (size_t)a[2];
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        char *list = a[1] ? memory(h, a[1], size) : NULL;
        if (a[1] && !list)
            return -1;
        return llistxattr(path, list, size);
    }
    case PX_LREMOVEXATTR: {
        char path_storage[BRIDGE_PATH_SIZE];
        const char *path = path_string_mode(h, a[0], path_storage, 0);
        if (!path)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        return lremovexattr(path, name);
    }
    case PX_FGETXATTR: {
        size_t size = (size_t)a[3];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return fgetxattr(descriptor, name, value, size);
    }
    case PX_FSETXATTR: {
        size_t size = (size_t)a[3];
        int flags = (int)a[4];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        const void *value = a[2] ? memory(h, a[2], size) : NULL;
        if (a[2] && !value)
            return -1;
        return fsetxattr(descriptor, name, value, size, flags);
    }
    case PX_FLISTXATTR: {
        size_t size = (size_t)a[2];
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        char *list = a[1] ? memory(h, a[1], size) : NULL;
        if (a[1] && !list)
            return -1;
        return flistxattr(descriptor, list, size);
    }
    case PX_FREMOVEXATTR: {
        int descriptor = fd(h, (int)a[0]);
        if (descriptor < 0)
            return -1;
        const char *name = string(h, a[1]);
        if (!name)
            return -1;
        return fremovexattr(descriptor, name);
    }
    default:
        return service_posix_extra(h, request);
    }
}
