/* Generated by scripts/generate-posix.py. */
int chown(const char *path, uid_t owner, gid_t group) {
    return posix_bridge(PX_CHOWN, (uintptr_t)path, (uint64_t)owner, (uint64_t)group, 0, 0, 0);
}
int lchown(const char *path, uid_t owner, gid_t group) {
    return posix_bridge(PX_LCHOWN, (uintptr_t)path, (uint64_t)owner, (uint64_t)group, 0, 0, 0);
}
int fchown(int descriptor, uid_t owner, gid_t group) {
    return posix_bridge(PX_FCHOWN, (uint64_t)descriptor, (uint64_t)owner, (uint64_t)group, 0, 0, 0);
}
int truncate(const char *path, off_t length) {
    return posix_bridge(PX_TRUNCATE, (uintptr_t)path, (uint64_t)length, 0, 0, 0, 0);
}
int ftruncate(int descriptor, off_t length) {
    return posix_bridge(PX_FTRUNCATE, (uint64_t)descriptor, (uint64_t)length, 0, 0, 0, 0);
}
ssize_t pread(int descriptor, void *buffer, size_t count, off_t offset) {
    return posix_bridge(PX_PREAD, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)count,
                        (uint64_t)offset, 0, 0);
}
ssize_t pwrite(int descriptor, const void *buffer, size_t count, off_t offset) {
    return posix_bridge(PX_PWRITE, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)count,
                        (uint64_t)offset, 0, 0);
}
ssize_t readlinkat(int directory, const char *path, char *buffer, size_t size) {
    return posix_bridge(PX_READLINKAT, (uint64_t)directory, (uintptr_t)path, (uintptr_t)buffer,
                        (uint64_t)size, 0, 0);
}
int unlinkat(int directory, const char *path, int flags) {
    return posix_bridge(PX_UNLINKAT, (uint64_t)directory, (uintptr_t)path, (uint64_t)flags, 0, 0,
                        0);
}
int flock(int descriptor, int operation) {
    return posix_bridge(PX_FLOCK, (uint64_t)descriptor, (uint64_t)operation, 0, 0, 0, 0);
}
int posix_fallocate(int descriptor, off_t offset, off_t length) {
    int rc = posix_bridge(PX_POSIX_FALLOCATE, (uint64_t)descriptor, (uint64_t)offset,
                          (uint64_t)length, 0, 0, 0);
    return rc < 0 ? errno : rc;
}
int mknod(const char *path, mode_t mode, dev_t device) {
    return posix_bridge(PX_MKNOD, (uintptr_t)path, (uint64_t)mode, (uint64_t)device, 0, 0, 0);
}
int utimes(const char *path, const struct timeval *times) {
    return posix_bridge(PX_UTIMES, (uintptr_t)path, (uintptr_t)times, 0, 0, 0, 0);
}
int futimens(int descriptor, const struct timespec *times) {
    return posix_bridge(PX_FUTIMENS, (uint64_t)descriptor, (uintptr_t)times, 0, 0, 0, 0);
}
pid_t getsid(pid_t process) {
    return posix_bridge(PX_GETSID, (uint64_t)process, 0, 0, 0, 0, 0);
}
int getpriority(int which, id_t who) {
    return posix_bridge(PX_GETPRIORITY, (uint64_t)which, (uint64_t)who, 0, 0, 0, 0);
}
int setpriority(int which, id_t who, int priority) {
    return posix_bridge(PX_SETPRIORITY, (uint64_t)which, (uint64_t)who, (uint64_t)priority, 0, 0,
                        0);
}
int sethostname(const char *name, size_t length) {
    return posix_bridge(PX_SETHOSTNAME, (uintptr_t)name, (uint64_t)length, 0, 0, 0, 0);
}
long gethostid(void) {
    return posix_bridge(PX_GETHOSTID, 0, 0, 0, 0, 0, 0);
}
int sched_get_priority_max(int policy) {
    return posix_bridge(PX_SCHED_GET_PRIORITY_MAX, (uint64_t)policy, 0, 0, 0, 0, 0);
}
int sched_get_priority_min(int policy) {
    return posix_bridge(PX_SCHED_GET_PRIORITY_MIN, (uint64_t)policy, 0, 0, 0, 0, 0);
}
int sched_getaffinity(pid_t process, size_t size, cpu_set_t *mask) {
    return posix_bridge(PX_SCHED_GETAFFINITY, (uint64_t)process, (uint64_t)size, (uintptr_t)mask, 0,
                        0, 0);
}
int sched_setaffinity(pid_t process, size_t size, const cpu_set_t *mask) {
    return posix_bridge(PX_SCHED_SETAFFINITY, (uint64_t)process, (uint64_t)size, (uintptr_t)mask, 0,
                        0, 0);
}
int socket(int domain, int type, int protocol) {
    return posix_bridge(PX_SOCKET, (uint64_t)domain, (uint64_t)type, (uint64_t)protocol, 0, 0, 0);
}
int bind(int descriptor, const struct sockaddr *address, socklen_t length) {
    return posix_bridge(PX_BIND, (uint64_t)descriptor, (uintptr_t)address, (uint64_t)length, 0, 0,
                        0);
}
int connect(int descriptor, const struct sockaddr *address, socklen_t length) {
    return posix_bridge(PX_CONNECT, (uint64_t)descriptor, (uintptr_t)address, (uint64_t)length, 0,
                        0, 0);
}
int listen(int descriptor, int backlog) {
    return posix_bridge(PX_LISTEN, (uint64_t)descriptor, (uint64_t)backlog, 0, 0, 0, 0);
}
int shutdown(int descriptor, int how) {
    return posix_bridge(PX_SHUTDOWN, (uint64_t)descriptor, (uint64_t)how, 0, 0, 0, 0);
}
ssize_t send(int descriptor, const void *buffer, size_t size, int flags) {
    return posix_bridge(PX_SEND, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)size,
                        (uint64_t)flags, 0, 0);
}
ssize_t recv(int descriptor, void *buffer, size_t size, int flags) {
    return posix_bridge(PX_RECV, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)size,
                        (uint64_t)flags, 0, 0);
}
ssize_t sendto(int descriptor, const void *buffer, size_t size, int flags,
               const struct sockaddr *address, socklen_t length) {
    return posix_bridge(PX_SENDTO, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)size,
                        (uint64_t)flags, (uintptr_t)address, (uint64_t)length);
}
int setsockopt(int descriptor, int level, int option, const void *value, socklen_t length) {
    return posix_bridge(PX_SETSOCKOPT, (uint64_t)descriptor, (uint64_t)level, (uint64_t)option,
                        (uintptr_t)value, (uint64_t)length, 0);
}
ssize_t getrandom(void *buffer, size_t size, unsigned int flags) {
    return posix_bridge(PX_GETRANDOM, (uintptr_t)buffer, (uint64_t)size, (uint64_t)flags, 0, 0, 0);
}
int inotify_init1(int flags) {
    return posix_bridge(PX_INOTIFY_INIT1, pack_flags(flags), 0, 0, 0, 0, 0);
}
int inotify_add_watch(int descriptor, const char *path, uint32_t mask) {
    return posix_bridge(PX_INOTIFY_ADD_WATCH, (uint64_t)descriptor, (uintptr_t)path, (uint64_t)mask,
                        0, 0, 0);
}
int inotify_rm_watch(int descriptor, int watch) {
    return posix_bridge(PX_INOTIFY_RM_WATCH, (uint64_t)descriptor, (uint64_t)watch, 0, 0, 0, 0);
}
int posix_openpt(int flags) {
    return posix_bridge(PX_POSIX_OPENPT, pack_flags(flags), 0, 0, 0, 0, 0);
}
int grantpt(int descriptor) {
    return posix_bridge(PX_GRANTPT, (uint64_t)descriptor, 0, 0, 0, 0, 0);
}
int unlockpt(int descriptor) {
    return posix_bridge(PX_UNLOCKPT, (uint64_t)descriptor, 0, 0, 0, 0, 0);
}
int ptsname_r(int descriptor, char *buffer, size_t size) {
    int rc = posix_bridge(PX_PTSNAME_R, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)size, 0,
                          0, 0);
    return rc < 0 ? errno : rc;
}
int ttyname_r(int descriptor, char *buffer, size_t size) {
    int rc = posix_bridge(PX_TTYNAME_R, (uint64_t)descriptor, (uintptr_t)buffer, (uint64_t)size, 0,
                          0, 0);
    return rc < 0 ? errno : rc;
}
int tcflow(int descriptor, int action) {
    return posix_bridge(PX_TCFLOW, (uint64_t)descriptor, (uint64_t)action, 0, 0, 0, 0);
}
int shm_unlink(const char *name) {
    return posix_bridge(PX_SHM_UNLINK, (uintptr_t)name, 0, 0, 0, 0, 0);
}
int clock_settime(clockid_t clock, const struct timespec *value) {
    return posix_bridge(PX_CLOCK_SETTIME, (uint64_t)clock, (uintptr_t)value, 0, 0, 0, 0);
}
int adjtime(const struct timeval *delta, struct timeval *old) {
    return posix_bridge(PX_ADJTIME, (uintptr_t)delta, (uintptr_t)old, 0, 0, 0, 0);
}
int reboot(int command) {
    return posix_bridge(PX_REBOOT, (uint64_t)command, 0, 0, 0, 0, 0);
}
int swapon(const char *path, int flags) {
    return posix_bridge(PX_SWAPON, (uintptr_t)path, (uint64_t)flags, 0, 0, 0, 0);
}
int swapoff(const char *path) {
    return posix_bridge(PX_SWAPOFF, (uintptr_t)path, 0, 0, 0, 0, 0);
}
int umount2(const char *path, int flags) {
    return posix_bridge(PX_UMOUNT2, (uintptr_t)path, (uint64_t)flags, 0, 0, 0, 0);
}
int setns(int descriptor, int type) {
    return posix_bridge(PX_SETNS, (uint64_t)descriptor, (uint64_t)type, 0, 0, 0, 0);
}
int unshare(int flags) {
    return posix_bridge(PX_UNSHARE, (uint64_t)flags, 0, 0, 0, 0, 0);
}
int rename(const char *old, const char *new) {
    return posix_bridge(PX_RENAME, (uintptr_t)old, (uintptr_t)new, 0, 0, 0, 0);
}
int memfd_create(const char *name, unsigned flags) {
    return posix_bridge(PX_MEMFD_CREATE, (uintptr_t)name, (uint64_t)flags, 0, 0, 0, 0);
}
int shm_open(const char *name, int flags, mode_t mode) {
    return posix_bridge(PX_SHM_OPEN, (uintptr_t)name, pack_flags(flags), (uint64_t)mode, 0, 0, 0);
}
int mount(const char *source, const char *target, const char *type, unsigned long flags,
          const void *data) {
    return posix_bridge(PX_MOUNT, (uintptr_t)source, (uintptr_t)target, (uintptr_t)type,
                        (uint64_t)flags, (uintptr_t)data, 0);
}
int initgroups(const char *user, gid_t group) {
    return posix_bridge(PX_INITGROUPS, (uintptr_t)user, (uint64_t)group, 0, 0, 0, 0);
}
int setgroups(int count, const gid_t *groups) {
    return posix_bridge(PX_SETGROUPS, (uint64_t)count, (uintptr_t)groups, 0, 0, 0, 0);
}
int setuid(uid_t id) {
    int rc = posix_bridge(PX_SETUID, (uint64_t)id, 0, 0, 0, 0, 0);
    return rc;
}
int setgid(gid_t id) {
    int rc = posix_bridge(PX_SETGID, (uint64_t)id, 0, 0, 0, 0, 0);
    return rc;
}
int setresuid(uid_t r, uid_t e, uid_t s) {
    int rc = posix_bridge(PX_SETRESUID, (uint64_t)r, (uint64_t)e, (uint64_t)s, 0, 0, 0);
    return rc;
}
int setresgid(gid_t r, gid_t e, gid_t s) {
    int rc = posix_bridge(PX_SETRESGID, (uint64_t)r, (uint64_t)e, (uint64_t)s, 0, 0, 0);
    return rc;
}
int setitimer(int which, const struct itimerval *value, struct itimerval *old) {
    return posix_bridge(PX_SETITIMER, (uint64_t)which, (uintptr_t)value, (uintptr_t)old, 0, 0, 0);
}
int statvfs(const char *path, struct statvfs *out) {
    return posix_bridge(PX_STATVFS, (uintptr_t)path, (uintptr_t)out, 0, 0, 0, 0);
}
int fstatvfs(int descriptor, struct statvfs *out) {
    return posix_bridge(PX_FSTATVFS, (uint64_t)descriptor, (uintptr_t)out, 0, 0, 0, 0);
}
int epoll_create1(int flags) {
    return posix_bridge(PX_EPOLL_CREATE1, pack_flags(flags), 0, 0, 0, 0, 0);
}
int epoll_wait(int descriptor, struct epoll_event *events, int count, int timeout) {
    return posix_bridge(PX_EPOLL_WAIT, (uint64_t)descriptor, (uintptr_t)events, (uint64_t)count,
                        (uint64_t)timeout, 0, 0);
}
int adjtimex(struct timex *value) {
    return posix_bridge(PX_ADJTIMEX, (uintptr_t)value, 0, 0, 0, 0, 0);
}
int sched_yield(void) {
    return posix_bridge(PX_SCHED_YIELD, 0, 0, 0, 0, 0, 0);
}
int pause(void) {
    return posix_bridge(PX_PAUSE, 0, 0, 0, 0, 0, 0);
}
int mlock(const void *address, size_t size) {
    return posix_bridge(PX_MLOCK, (uintptr_t)address, (uint64_t)size, 0, 0, 0, 0);
}
int munlock(const void *address, size_t size) {
    return posix_bridge(PX_MUNLOCK, (uintptr_t)address, (uint64_t)size, 0, 0, 0, 0);
}
int mlockall(int flags) {
    return posix_bridge(PX_MLOCKALL, (uint64_t)flags, 0, 0, 0, 0, 0);
}
int munlockall(void) {
    return posix_bridge(PX_MUNLOCKALL, 0, 0, 0, 0, 0, 0);
}
int msgget(key_t key, int flags) {
    return posix_bridge(PX_MSGGET, (uint64_t)key, (uint64_t)flags, 0, 0, 0, 0);
}
int shmget(key_t key, size_t size, int flags) {
    return posix_bridge(PX_SHMGET, (uint64_t)key, (uint64_t)size, (uint64_t)flags, 0, 0, 0);
}
int semget(key_t key, int count, int flags) {
    return posix_bridge(PX_SEMGET, (uint64_t)key, (uint64_t)count, (uint64_t)flags, 0, 0, 0);
}
int chroot(const char *path) {
    return posix_bridge(PX_CHROOT, (uintptr_t)path, 0, 0, 0, 0, 0);
}
int utimensat(int directory, const char *path, const struct timespec *times, int flags) {
    return posix_bridge(PX_UTIMENSAT, (uint64_t)directory, (uintptr_t)path, (uintptr_t)times,
                        (uint64_t)flags, 0, 0);
}
int clock_getres(clockid_t clock, struct timespec *value) {
    return posix_bridge(PX_CLOCK_GETRES, (uint64_t)clock, (uintptr_t)value, 0, 0, 0, 0);
}
clock_t times(struct tms *value) {
    return posix_bridge(PX_TIMES, (uintptr_t)value, 0, 0, 0, 0, 0);
}
int faccessat(int directory, const char *path, int mode, int flags) {
    return posix_bridge(PX_FACCESSAT, (uint64_t)directory, (uintptr_t)path, (uint64_t)mode,
                        (uint64_t)flags, 0, 0);
}
ssize_t getxattr(const char *path, const char *name, void *value, size_t size) {
    return posix_bridge(PX_GETXATTR, (uintptr_t)path, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, 0, 0);
}
int setxattr(const char *path, const char *name, const void *value, size_t size, int flags) {
    return posix_bridge(PX_SETXATTR, (uintptr_t)path, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, (uint64_t)flags, 0);
}
ssize_t listxattr(const char *path, char *list, size_t size) {
    return posix_bridge(PX_LISTXATTR, (uintptr_t)path, (uintptr_t)list, (uint64_t)size, 0, 0, 0);
}
int removexattr(const char *path, const char *name) {
    return posix_bridge(PX_REMOVEXATTR, (uintptr_t)path, (uintptr_t)name, 0, 0, 0, 0);
}
ssize_t lgetxattr(const char *path, const char *name, void *value, size_t size) {
    return posix_bridge(PX_LGETXATTR, (uintptr_t)path, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, 0, 0);
}
int lsetxattr(const char *path, const char *name, const void *value, size_t size, int flags) {
    return posix_bridge(PX_LSETXATTR, (uintptr_t)path, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, (uint64_t)flags, 0);
}
ssize_t llistxattr(const char *path, char *list, size_t size) {
    return posix_bridge(PX_LLISTXATTR, (uintptr_t)path, (uintptr_t)list, (uint64_t)size, 0, 0, 0);
}
int lremovexattr(const char *path, const char *name) {
    return posix_bridge(PX_LREMOVEXATTR, (uintptr_t)path, (uintptr_t)name, 0, 0, 0, 0);
}
ssize_t fgetxattr(int descriptor, const char *name, void *value, size_t size) {
    return posix_bridge(PX_FGETXATTR, (uint64_t)descriptor, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, 0, 0);
}
int fsetxattr(int descriptor, const char *name, const void *value, size_t size, int flags) {
    return posix_bridge(PX_FSETXATTR, (uint64_t)descriptor, (uintptr_t)name, (uintptr_t)value,
                        (uint64_t)size, (uint64_t)flags, 0);
}
ssize_t flistxattr(int descriptor, char *list, size_t size) {
    return posix_bridge(PX_FLISTXATTR, (uint64_t)descriptor, (uintptr_t)list, (uint64_t)size, 0, 0,
                        0);
}
int fremovexattr(int descriptor, const char *name) {
    return posix_bridge(PX_FREMOVEXATTR, (uint64_t)descriptor, (uintptr_t)name, 0, 0, 0, 0);
}
